"""
Ray-wave-ray DOE plane surface, bounded-complexity version.

Main difference from old DoeRaywave:
    Old: each incoming ray extracts a local patch, FFTs it, then branches into spr rays.
    New: all incoming coherent rays are first accumulated into one complex field on the
         DOE plane, the DOE interacts with that whole field, then outgoing rays are
         sampled as:

             out_primary_ray_count x sampled_secondary_ray_count

         Primary rays define sampled output positions on the DOE plane.
         Secondary rays define sampled angular-spectrum directions from each primary
         position. Total outgoing rays = primary_count * secondary_count.

This is intended for stacked DOEs, where local per-ray branching can explode.
"""

import math
import numpy as np
import torch
import torch.nn.functional as F

from deeplens.geometric_surface.plane import Plane
from deeplens.light.ray import Ray

try:
    from deeplens.config import EPSILON as EPS
except Exception:
    EPS = 1e-12


def _fft2c(x: torch.Tensor) -> torch.Tensor:
    """Centered 2D FFT over the last two dimensions."""
    return torch.fft.fftshift(
        torch.fft.fft2(torch.fft.ifftshift(x, dim=(-2, -1)), dim=(-2, -1)),
        dim=(-2, -1),
    )


def _ifft2c(x: torch.Tensor) -> torch.Tensor:
    """Centered 2D inverse FFT over the last two dimensions."""
    return torch.fft.fftshift(
        torch.fft.ifft2(torch.fft.ifftshift(x, dim=(-2, -1)), dim=(-2, -1)),
        dim=(-2, -1),
    )


def _real_dtype_like(x: torch.Tensor) -> torch.dtype:
    if x.is_complex():
        return x.real.dtype
    return x.dtype if x.dtype in (torch.float32, torch.float64) else torch.float32


def _complex_dtype_from_real(real_dtype: torch.dtype) -> torch.dtype:
    return torch.complex64 if real_dtype == torch.float32 else torch.complex128


def _nan_to_num_complex(z: torch.Tensor, nan=0.0, posinf=0.0, neginf=0.0) -> torch.Tensor:
    return torch.complex(
        torch.nan_to_num(z.real, nan=nan, posinf=posinf, neginf=neginf),
        torch.nan_to_num(z.imag, nan=nan, posinf=posinf, neginf=neginf),
    )


def _sample_2d_pdf(pdf: torch.Tensor, num_samples: int, eps: float = 1e-7) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Sample from a 2D PDF without flattening H*W categories.

    Returns:
        y_idx: [num_samples]
        x_idx: [num_samples]
        pdf_s: [num_samples], sampled joint probability p(y, x)
    """
    if pdf.ndim != 2:
        raise ValueError(f"Expected pdf [H, W], got {tuple(pdf.shape)}")

    pdf = torch.nan_to_num(pdf, nan=0.0, posinf=0.0, neginf=0.0).clamp_min(0.0)
    total = pdf.sum()

    if total <= 0:
        H, W = pdf.shape
        y_idx = torch.full((num_samples,), H // 2, device=pdf.device, dtype=torch.long)
        x_idx = torch.full((num_samples,), W // 2, device=pdf.device, dtype=torch.long)
        pdf_s = torch.full((num_samples,), 1.0 / (H * W), device=pdf.device, dtype=pdf.dtype)
        return y_idx, x_idx, pdf_s

    # 1. Normalize the joint PDF
    pdf = pdf / total.clamp_min(eps)

    # 2. Sample y from marginal p(y)
    pdf_y = pdf.sum(dim=1)  # [H]
    y_idx = torch.multinomial(pdf_y, num_samples, replacement=True)

    # 3. Sample x from conditional p(x | y)
    pdf_x_given_y = pdf[y_idx, :]  # [num_samples, W]
    row_sums = pdf_x_given_y.sum(dim=1, keepdim=True)
    
    # Safety: If a row sums to 0, make it a uniform distribution so multinomial doesn't crash
    safe_sums = torch.where(row_sums > 0, row_sums, torch.ones_like(row_sums))
    pdf_x_given_y = torch.where(row_sums > 0, pdf_x_given_y / safe_sums, torch.ones_like(pdf_x_given_y) / pdf.shape[1])
    
    x_idx = torch.multinomial(pdf_x_given_y, 1, replacement=True).squeeze(1)

    # 4. Direct lookup for joint p(y, x)
    pdf_s = pdf[y_idx, x_idx]

    return y_idx, x_idx, pdf_s


class DoeRaywavePlane(Plane):
    """
    DOE plane using a ray -> field -> DOE -> ray operator.

    The DOE stores a complex transmission field on a centered physical xy grid.
    Incoming coherent rays are accumulated onto this grid using a Huygens/plane-wave
    Fourier splat. The DOE multiplies the full complex field. Outgoing rays are then
    generated by:

        1. choosing primary ray positions (resampled from the output xy grid, or kept
           at incoming ray locations when reset_primary_ray is False);
        2. randomly sampling secondary angular-spectrum directions for each primary;
        3. assigning coherent amplitudes with the Fourier-shift phase correction
           for each primary location.

    Total outgoing ray count:

        out_primary_ray_count * sampled_secondary_ray_count

    Assumptions:
        - Plane DOE at z = d.
        - Square field grid.
        - dx == dy for the current Huygens splat.
        - Single wavelength per ray-to-field conversion.
    """

    def __init__(
        self,
        d: float,
        r: float = 5.0,
        mat2: str = "air",
        device: str = "cpu",
        field: torch.Tensor | None = None,
        dx: float | None = None,
        dy: float | None = None,
        origin_xy: tuple[float, float] = (0.0, 0.0),
        pad_flat: bool = True,
        out_primary_ray_count: int = 1024,
        sampled_secondary_ray_count: int = 4,
        reset_primary_ray: bool = True,
        preserve_energy: bool = True,
        is_tracing: bool = False,
        is_square: bool = False,
    ):
        """
        Args:
            d: Plane position along z. [mm]
            r: Aperture radius. [mm]
            mat2: Material after the surface.
            device: torch device.
            field: Complex DOE transmission [H, W], or real phase map in radians.
            dx: DOE pixel pitch along x. [mm/pixel]
            dy: DOE pixel pitch along y. [mm/pixel]
            origin_xy: Physical center of the DOE grid. [mm]
            pad_flat: If True, pad by half-size on each side:
                100 x 100 -> 200 x 200,
                101 x 101 -> 201 x 201.
            out_primary_ray_count: Number of sampled primary output positions. Ignored when
                reset_primary_ray is False.
            sampled_secondary_ray_count: Number of angular-spectrum samples per primary.
            reset_primary_ray: If True, randomly resample primary output positions from
                the DOE xy grid. If False, keep each primary at its incoming ray xy
                location and ignore out_primary_ray_count.
            preserve_energy: Renormalize output field power to input field power after
                pure DOE multiplication.
            is_tracing: If True, trace rays through the DOE plane.
            is_square: Use square Plane aperture if True.
        """
        super().__init__(r=r, d=d, mat2=mat2, is_square=is_square, device=device)
        self.device = torch.device(device)

        self.field = None
        self.dx = dx
        self.dy = dy
        self.origin_xy = (float(origin_xy[0]), float(origin_xy[1]))
        self.pad_flat = bool(pad_flat)
        self.out_primary_ray_count = int(out_primary_ray_count)
        self.sampled_secondary_ray_count = int(sampled_secondary_ray_count)
        self.reset_primary_ray = bool(reset_primary_ray)
        self.preserve_energy = bool(preserve_energy)
        self.design_r = float(r)
        self._is_complex_field = False
        self.is_tracing = bool(is_tracing)
        if self.reset_primary_ray and self.out_primary_ray_count <= 0:
            raise ValueError("out_primary_ray_count must be positive when reset_primary_ray is True.")
        if self.sampled_secondary_ray_count <= 0:
            raise ValueError("sampled_secondary_ray_count must be positive.")

        if field is not None:
            self.set_grid(field, dx, dy, origin_xy)

    # -------------------------------------------------------------------------
    # Grid registration
    # -------------------------------------------------------------------------
    def set_grid(self, field: torch.Tensor, dx: float, dy: float, origin_xy=(0.0, 0.0)):
        """Register a complex DOE transmission map or a real phase map."""
        if field.ndim != 2:
            raise ValueError("field must have shape [H, W].")
        if dx is None or dy is None:
            raise ValueError("dx and dy must be provided.")

        self.dx = float(dx)
        self.dy = float(dy)
        self.origin_xy = (float(origin_xy[0]), float(origin_xy[1]))

        field = field.to(self.device)
        if field.is_complex():
            complex_field = field
        else:
            real_dtype = _real_dtype_like(field)
            cplx_dtype = _complex_dtype_from_real(real_dtype)
            complex_field = torch.exp(1j * field.to(cplx_dtype))

        if self.pad_flat:
            complex_field = self._pad_field_flat(complex_field)

        self.field = complex_field
        self._is_complex_field = True
        self.Xg, self.Yg = self._xy_axes_centered(self.field.shape[0], self.field.shape[1])
        self._update_encoded_radius()

    def has_grid(self) -> bool:
        return self.field is not None and self.dx is not None and self.dy is not None

    def _pad_field_flat(self, field: torch.Tensor) -> torch.Tensor:
        """
        Pad field by half-size on each side.

        Examples:
            H = 100 -> top 50, bottom 50 -> 200
            H = 101 -> top 50, bottom 50 -> 201

        This keeps the original field centered and gives a larger flat zero-padded
        computational aperture for the field-domain interaction.
        """
        H, W = field.shape
        pad_y = H // 2
        pad_x = W // 2
        return F.pad(field, (pad_x, pad_x, pad_y, pad_y), mode="constant", value=0)

    def _update_encoded_radius(self):
        if not self.has_grid():
            return
        H, W = self.field.shape
        rx = W * self.dx * 0.5
        ry = H * self.dy * 0.5
        self.r = float(min(rx, ry))
        self.l = self.r * np.sqrt(2)

    def _xy_axes_centered(self, H: int, W: int):
        real_dtype = _real_dtype_like(self.field.real)
        x0, y0 = self.origin_xy
        xs = x0 + (torch.arange(W, device=self.device, dtype=real_dtype) - (W - 1) / 2) * self.dx
        ys = y0 + (torch.arange(H, device=self.device, dtype=real_dtype) - (H - 1) / 2) * self.dy
        return xs, ys

    # -------------------------------------------------------------------------
    # Main optical reaction
    # -------------------------------------------------------------------------
    def ray_reaction(self, ray: Ray, n1=1.0, n2=1.0):
        """Intersect the plane, convert ray bundle to field, apply DOE, resample rays."""
        ray = self.intersect(ray, n1)
        if self.is_tracing:
            return self.refract_raywave_field(ray, n1=n1, n2=n2)
        else:
            return self.refract(ray, eta=n1/n2)

    def refract_raywave_field(self, ray: Ray, n1=1.0, n2=1.0):
        """
        Bounded ray-wave-ray DOE interaction.

        Pipeline:
            1. Flatten valid incoming rays after plane intersection.
            2. Accumulate them into a complex input field on the DOE grid.
            3. Multiply by the DOE transmission field.
            4. FFT the output field to get the global angular spectrum.
            5. Randomly sample primary positions from the xy grid.
            6. For each primary position, randomly sample secondary directions from
               the angular spectrum and assign coherent amplitudes.
        """
        assert self.has_grid(), "Call set_grid(field, dx, dy, origin_xy) first."

        n_slots = ray.o[..., 0].numel()
        valid_1d = (ray.is_valid > 0).reshape(n_slots)
        if not torch.any(valid_1d):
            return ray

        o = ray.o.reshape(-1, 3)[valid_1d]
        d_in = ray.d.reshape(-1, 3)[valid_1d]
        wvln_um = ray.wvln.item()
        opl = ray.opl.view(n_slots, -1)[valid_1d].squeeze(-1)

        if hasattr(ray, "amp"):
            amp = ray.amp.reshape(-1)[valid_1d]
        else:
            amp = None

        E_in = self._ray_to_field_huygens(
            o=o,
            d=d_in,
            opl=opl,
            wvln_um=wvln_um,
            amp=amp,
            n_ref=n1,
        )

        E_out = _nan_to_num_complex(E_in * self.field)

        if self.preserve_energy:
            pin = (E_in.abs() ** 2).sum().clamp_min(EPS)
            pout = (E_out.abs() ** 2).sum().clamp_min(EPS)
            E_out = E_out * torch.sqrt(pin / pout).to(E_out.real.dtype)

        return self._field_to_primary_secondary_rays(
            E_out=E_out,
            wvln_um=wvln_um,
            n2=n2,
            parent_en=ray.en.view(n_slots, -1)[valid_1d].squeeze(-1),
            input_xy=o[:, :2] if not self.reset_primary_ray else None,
        )
 
    # -------------------------------------------------------------------------
    # Ray -> field: Huygens/PSF Fourier splatting
    # -------------------------------------------------------------------------
    def _ray_to_field_huygens(
        self,
        o: torch.Tensor,
        d: torch.Tensor,
        opl: torch.Tensor,
        wvln_um: torch.Tensor,
        amp: torch.Tensor | None,
        n_ref=1.0,
    ) -> torch.Tensor:
        """
        Convert a coherent ray bundle into a complex field on the DOE grid.

        This follows the Huygens PSF structure:
            - complex weights from amp, OPL, and ray-position piston;
            - bilinear splat into angular spectrum;
            - inverse FFT back to spatial field.
        """
        H, W = self.field.shape
        if H != W:
            raise ValueError("Current ray_to_field splat assumes a square DOE grid.")
        if abs(float(self.dx) - float(self.dy)) > 1e-12:
            raise ValueError("Current ray_to_field splat assumes dx == dy.")

        device = self.device
        real_dtype = _real_dtype_like(o)
        cplx_dtype = _complex_dtype_from_real(real_dtype)
        ks = H
        pp = float(self.dx)

        if torch.is_tensor(n_ref):
            n_val = n_ref.reshape(-1)[0].to(device=device, dtype=real_dtype)
        else:
            n_val = torch.tensor(float(n_ref), device=device, dtype=real_dtype)

        wvln_mm = (wvln_um * 1e-3)
        k = n_val * (2.0 * math.pi / wvln_mm)

        d_norm = d / torch.linalg.norm(d, dim=-1, keepdim=True).clamp_min(EPS)
        kx_s = k * d_norm[:, 0]
        ky_s = k * d_norm[:, 1]

        ox = o[:, 0] - self.origin_xy[0]
        oy = o[:, 1] - self.origin_xy[1]
        piston = -(kx_s * ox + ky_s * oy)

        if amp is None:
            amp_c = torch.ones((o.shape[0],), dtype=cplx_dtype, device=device)
        else:
            amp_c = amp.squeeze()
            if not torch.is_complex(amp_c):
                amp_c = amp_c.to(device=device, dtype=cplx_dtype)
            else:
                amp_c = amp_c.to(device=device, dtype=cplx_dtype)

        phase = torch.exp(1j * ((k * opl).to(cplx_dtype) + piston.to(cplx_dtype)))
        A = amp_c * phase

        fx = torch.fft.fftshift(torch.fft.fftfreq(ks, d=pp)).to(device=device, dtype=real_dtype)
        kx_grid = 2 * math.pi * fx
        dk = (kx_grid[1] - kx_grid[0]).abs().clamp_min(EPS)
        kmax = math.pi / pp
        kmax_eff = kmax - dk

        inband = (kx_s.abs() < kmax_eff) & (ky_s.abs() < kmax_eff)
        if not torch.any(inband):
            return torch.zeros((ks, ks), dtype=cplx_dtype, device=device)

        kx_s = kx_s[inband]
        ky_s = ky_s[inband]
        A = A[inband]

        center = ks // 2
        ix_f = kx_s / dk + center
        iy_f = ky_s / dk + center

        valid = (ix_f >= 0) & (ix_f <= ks - 2) & (iy_f >= 0) & (iy_f <= ks - 2)
        if not torch.any(valid):
            return torch.zeros((ks, ks), dtype=cplx_dtype, device=device)

        ix_f = ix_f[valid]
        iy_f = iy_f[valid]
        A = A[valid]

        ix0 = torch.floor(ix_f).long()
        iy0 = torch.floor(iy_f).long()
        tx = ix_f - ix0.to(ix_f.dtype)
        ty = iy_f - iy0.to(iy_f.dtype)

        ix1 = ix0 + 1
        iy1 = iy0 + 1
        w00 = (1 - tx) * (1 - ty)
        w10 = tx * (1 - ty)
        w01 = (1 - tx) * ty
        w11 = tx * ty

        def lin(ix, iy):
            return iy * ks + ix

        idx00 = lin(ix0, iy0)
        idx10 = lin(ix1, iy0)
        idx01 = lin(ix0, iy1)
        idx11 = lin(ix1, iy1)

        Ehat_r = torch.zeros((ks * ks,), dtype=real_dtype, device=device)
        Ehat_i = torch.zeros((ks * ks,), dtype=real_dtype, device=device)

        Ar = A.real.to(real_dtype)
        Ai = A.imag.to(real_dtype)
        Ehat_r.index_add_(0, idx00, w00 * Ar)
        Ehat_r.index_add_(0, idx10, w10 * Ar)
        Ehat_r.index_add_(0, idx01, w01 * Ar)
        Ehat_r.index_add_(0, idx11, w11 * Ar)
        Ehat_i.index_add_(0, idx00, w00 * Ai)
        Ehat_i.index_add_(0, idx10, w10 * Ai)
        Ehat_i.index_add_(0, idx01, w01 * Ai)
        Ehat_i.index_add_(0, idx11, w11 * Ai)

        Ehat = torch.complex(Ehat_r, Ehat_i).view(ks, ks)
        field = _ifft2c(Ehat)
        return _nan_to_num_complex(field)

    # -------------------------------------------------------------------------
    # Field -> rays: primary positions x secondary sampled directions
    # -------------------------------------------------------------------------
    def _field_to_primary_secondary_rays(
        self,
        E_out: torch.Tensor,
        wvln_um: torch.Tensor,
        n2=1.0,
        parent_en: torch.Tensor | None = None,
        input_xy: torch.Tensor | None = None,
    ) -> Ray:
        """
        Sample outgoing rays from the output complex field.

        Primary rays:
            If reset_primary_ray is True, randomly sampled positions from the xy grid.
            Otherwise, the incoming ray xy locations passed via input_xy.

        Secondary rays:
            For each primary position, randomly sample sampled_secondary_ray_count
            directions from the global angular spectrum amplitude PDF.

        Output ordering:
            rays[0:S] are secondary rays from primary 0,
            rays[S:2S] are secondary rays from primary 1,
            etc.
        """
        H, W = E_out.shape
        if H != W:
            raise ValueError("Current field_to_rays assumes a square output field.")
        if abs(float(self.dx) - float(self.dy)) > 1e-12:
            raise ValueError("Current field_to_rays assumes dx == dy.")

        device = self.device
        real_dtype = _real_dtype_like(E_out.real)
        cplx_dtype = _complex_dtype_from_real(real_dtype)

        S = self.sampled_secondary_ray_count

        if self.reset_primary_ray:
            P = self.out_primary_ray_count
            xy_primary, _ = self._sample_primary_xy_from_grid(P)
        else:
            if input_xy is None:
                raise ValueError("input_xy is required when reset_primary_ray is False.")
            xy_primary = input_xy.to(device=device, dtype=real_dtype)
            P = xy_primary.shape[0]

        N = P * S
        xy = xy_primary.repeat_interleave(S, dim=0)

        z = torch.full((N, 1), float(self.d), dtype=real_dtype, device=device)
        o_s = torch.cat([xy, z], dim=-1)

        # 2. Build angular spectrum from the full output field.
        spec = _fft2c(E_out)

        fx = torch.fft.fftshift(torch.fft.fftfreq(H, d=float(self.dx))).to(device=device, dtype=real_dtype)
        fy = torch.fft.fftshift(torch.fft.fftfreq(W, d=float(self.dy))).to(device=device, dtype=real_dtype)
        Fx, Fy = torch.meshgrid(fx, fy, indexing="xy")
        Kx = 2 * math.pi * Fx
        Ky = 2 * math.pi * Fy

        if torch.is_tensor(n2):
            n2v = n2.reshape(-1)[0].to(device=device, dtype=real_dtype)
        else:
            n2v = torch.tensor(float(n2), device=device, dtype=real_dtype)

        wvln_mm = (wvln_um * 1e-3)
        k_exit = n2v * (2 * math.pi / wvln_mm)
        prop_mask = (Kx ** 2 + Ky ** 2) < (k_exit ** 2)

        pdf = spec.abs() * prop_mask
        pdf = torch.nan_to_num(pdf, nan=0.0, posinf=0.0, neginf=0.0)
        if pdf.sum() <= 0:
            pdf = torch.zeros_like(pdf)
            pdf[H // 2, W // 2] = 1.0
        pdf = pdf / pdf.sum().clamp_min(EPS)

        # Sample P x S directions without flattening H*W categories;
        # flat multinomial over the full grid is slow and can hit CUDA category limits.
        y_idx, x_idx, pdf_s = _sample_2d_pdf(pdf, N)

        kx_s = Kx[y_idx, x_idx]
        ky_s = Ky[y_idx, x_idx]
        spec_s = spec[y_idx, x_idx].to(cplx_dtype)
        pdf_s = pdf_s.to(real_dtype).clamp_min(EPS)

        dx_dir = kx_s / k_exit.clamp_min(EPS)
        dy_dir = ky_s / k_exit.clamp_min(EPS)
        dz_dir = torch.sqrt((1.0 - dx_dir ** 2 - dy_dir ** 2).clamp_min(0.0))
        d_s = torch.stack([dx_dir, dy_dir, dz_dir], dim=-1)
        d_s = F.normalize(d_s, dim=-1)

        # 4. Correct amplitude for each ray based on its primary ray location.
        #    rays[0:S] belong to primary 0, etc.
        x_rel = xy[:, 0] - self.origin_xy[0]
        y_rel = xy[:, 1] - self.origin_xy[1]
        shift_phase = torch.exp(1j * (kx_s * x_rel + ky_s * y_rel).to(cplx_dtype))

        # Unnormalized FFT convention, amplitude-PDF importance sampling.
        area = float(self.dx * self.dy)
        amps = spec_s * shift_phase * (area / pdf_s.to(cplx_dtype).detach()) / float(N)
        amps = _nan_to_num_complex(amps.reshape(-1))

        new_ray = Ray(o_s, d_s, wvln=wvln_um, is_coherent=True, device=device)
        new_ray.is_valid = torch.ones((N,), dtype=real_dtype, device=device)
        new_ray.is_forward = (new_ray.d[..., 2].unsqueeze(-1) > 0)
        new_ray.amp = amps
        new_ray.opl = torch.zeros((N, 1), dtype=real_dtype, device=device)

        if parent_en is not None and parent_en.numel() > 0:
            en_mean = parent_en.mean().to(real_dtype)
            new_ray.en = torch.full((N, 1), en_mean, dtype=real_dtype, device=device)
        else:
            new_ray.en = torch.ones((N, 1), dtype=real_dtype, device=device)

        return new_ray

    def _sample_primary_xy_from_grid(self, primary_count: int):
        """
        Randomly sample primary ray positions from the DOE xy grid.

        Returns:
            xy_primary: [primary_count, 2] physical xy positions.
            idx: [primary_count] flattened pixel indices.
        """
        H, W = self.field.shape
        xs, ys = self._xy_axes_centered(H, W)
        X, Y = torch.meshgrid(xs, ys, indexing="xy")
        xy_all = torch.stack([X.reshape(-1), Y.reshape(-1)], dim=-1)
        n_pix = xy_all.shape[0]
        idx = torch.randint(0, n_pix, (primary_count,), device=self.device)
        return xy_all[idx], idx

    # -------------------------------------------------------------------------
    # Serialization / visualization
    # -------------------------------------------------------------------------
    @classmethod
    def init_from_dict(cls, surf_dict):
        return cls(
            d=surf_dict["d"],
            r=surf_dict.get("design_r", surf_dict.get("r", 5.0)),
            mat2=surf_dict.get("mat2", "air"),
            device=surf_dict.get("device", "cpu"),
            field=surf_dict.get("field", None),
            dx=surf_dict.get("dx", None),
            dy=surf_dict.get("dy", None),
            origin_xy=tuple(surf_dict.get("origin_xy", (0.0, 0.0))),
            pad_flat=bool(surf_dict.get("pad_flat", True)),
            out_primary_ray_count=int(surf_dict.get("out_primary_ray_count", 1024)),
            sampled_secondary_ray_count=int(surf_dict.get("sampled_secondary_ray_count", 4)),
            reset_primary_ray=bool(surf_dict.get("reset_primary_ray", True)),
            preserve_energy=bool(surf_dict.get("preserve_energy", True)),
            is_square=bool(surf_dict.get("is_square", False)),
        )

    def surf_dict(self):
        surf_dict = {
            "type": "DoeRaywaveNew",
            "r": self.r,
            "design_r": self.design_r,
            "(d)": round(self.d.item(), 4) if hasattr(self.d, "item") else round(float(self.d), 4),
            "d": self.d,
            "is_square": self.is_square,
            "mat2": self.mat2.get_name() if hasattr(self.mat2, "get_name") else self.mat2,
            "dx": self.dx,
            "dy": self.dy,
            "origin_xy": self.origin_xy,
            "pad_flat": self.pad_flat,
            "out_primary_ray_count": self.out_primary_ray_count,
            "sampled_secondary_ray_count": self.sampled_secondary_ray_count,
            "reset_primary_ray": self.reset_primary_ray,
            "preserve_energy": self.preserve_energy,
        }
        return surf_dict

    def draw_widget(self, ax, color="black", linestyle="-"):
        super().draw_widget(ax, color, linestyle)
        if self.field is not None:
            H, W = self.field.shape
            xs, ys = self._xy_axes_centered(H, W)
            extent = [
                float(xs[0] - self.dx * 0.5),
                float(xs[-1] + self.dx * 0.5),
                float(ys[0] - self.dy * 0.5),
                float(ys[-1] + self.dy * 0.5),
            ]
            ax.imshow(
                torch.angle(self.field).detach().cpu().numpy(),
                extent=extent,
                origin="lower",
                cmap="twilight",
                alpha=0.25,
            )
