wavelength_um: 0.7

source:
  z_mm: -1.0
  num_input_rays: 128

surfaces:
  - type: raywave_doe
    name: doe
    z_mm: 0.0
    grid_size: 200
    pitch_mm: 0.0063
    aperture_radius_mm: null
    origin_xy_mm: [0.0, 0.0]
    phase_profile: optimizable
    out_primary_ray_count: 2
    sampled_secondary_ray_count: 16384
    preserve_energy: true
    n_before: 1.0
    n_after: 1.0
    ray_sampling: gumbel
    gumbel_tau: 3.0
    gumbel_straight_through: true

  - type: refractive
    name: lens_front
    shape: spherical
    z_mm: 3.0
    aperture_radius_mm: 12.7
    curvature_mm_inv: 0.03875968992248062
    n_before: 1.0
    n_after: 1.5131

  - type: refractive
    name: lens_back
    shape: flat
    z_mm: 8.3
    aperture_radius_mm: 12.7
    curvature_mm_inv: 0.0
    n_before: 1.5131
    n_after: 1.0

sensor:
  z_mm: 53.0
  grid_size: 200
  pitch_mm: 0.0063
  oversamp: 2.0
  n_before: 1.0
